name: make-mermaid
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build slims"]
    types:
      - completed
  
jobs:
    robot-workflows:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: get robot
          run: |
            ls
            wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
            wget https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar
            chmod 777 robo*
            mkdir -p robot-report
    
        - name: merge
          run: | 
            sh robot merge -i enanomapper-dev.owl -o enanomapper-dev-full.owl
            sh robot merge -i enanomapper.owl -o enanomapper-full.owl
            
        - name: "make mermaid"
          run: |
            python scripts/src/build-workflow/make-mmd.py
            mv subclass.md scripts/src/build-workflow/subclass.md
            git add scripts/src/build-workflow/subclass.md
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Actions - update mermaid" scripts/src/build-workflow/subclass.md
            git push -f
