name: ROBOT-commands
on:
  workflow_dispatch:
    
  workflow_run:
    workflows: ["Build slims"]
    types:
      - completed
    

jobs:
    robot-workflows:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: get robot
          run: |
            ls
            wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
            wget https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar
            chmod 777 robo*
            mkdir -p robot-report
    
        - name: merge
          run: | 
            sh robot merge -i enanomapper-dev.owl -o enanomapper-dev-full.owl
            sh robot merge -i enanomapper.owl -o enanomapper-full.owl
            
  # Upload owl artifacts
        - name: 'Upload enanomapper* artifacts'
          uses: actions/upload-artifact@v3
          with:
            name: enanomapper-files
            path: enanomapper*
  
        - name: rm temp owl files
          run: |
            rm enanomapper-full.owl
            rm enanomapper-dev-full.owl
            
        - name: report
          run: sh robot report --fail-on none -i enanomapper-dev-full.owl -o robot-report/report.tsv
        - name: diff
          run: |
            sh robot diff --left enanomapper-full.owl --right enanomapper-dev-full.owl --output robot-report/diff.txt
        - name: 'Upload report'
          uses: actions/upload-artifact@v3
          with:
            name: report
            path: ./robot-report/* 
            