name: Build slims
on:
  workflow_dispatch:
  schedule:
    - cron: 1 0 1 1-12 *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    # Get slimmer and robot
    - name: get slimmer
      run: wget -nc https://github.com/enanomapper/slimmer/releases/download/v1.0.2/slimmer-1.0.2-jar-with-dependencies.jar
    - name: get robot
      run: |
        cd ./scripts/src/build-workflow
        wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
        wget https://github.com/ontodev/robot/releases/download/v1.9.0/robot.jar
        chmod 777 robo*
  
  # slim all ontologies
  # Authorize running slim script
    - name: authorize running slim scripts
      run: chmod 755 scripts/src/build-workflow/*.sh
  
  # Slim bfo
    - name: slim-bfo
      run: bash scripts/src/build-workflow/slim.sh bfo
  
  # Slim npo
    - name: slim-npo
      run: bash scripts/src/build-workflow/slim.sh npo
  
  # apply props bao
    - name: Apply props bao
      run: bash scripts/src/build-workflow/props.sh bao
  
  # apply props npo
    - name: Apply props npo
      run: bash scripts/src/build-workflow/props.sh npo
  
  # Commit and push
    - name: Commit OWL files
      run: |
        git add external-dev/*.owl
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Actions - slim updated" ./external-dev/*.owl
        git push -f
  