name: update repository
permissions: write-all
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
    paths:
     - 'scripts/src/build-workflow/**'
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
       token: ${{ secrets.GITHUB_TOKEN }} 
    - name: update according to new yaml settings
      run:  |
        cd scripts/src/build-workflow 
        python makeBuild.py
        python makeROBOT.py
        cd ../../../

    - name: Set up ssh-agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PAT }}   ## needed for pushing into .github/workflows

    - name: commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/workflows/*.yml
        git add -A
        if ! git diff-index --quiet HEAD; then
          git commit -m "Updated workflow" .github/workflows/*.yml
          git push
        fi
